kind = "mobile"
previewPath = "/"
title = "TAXbuddy"
version = "1.0.0"
id = "artifacts/taxbuddy"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18505

[services.development]
run = "pnpm --filter @workspace/taxbuddy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/taxbuddy", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/taxbuddy", "run", "serve" ]

[services.env]
PORT = "18505"
BASE_PATH = "/"
