// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/taxbuddy-dashboard/UsabilityA.tsx": () => import("../components/mockups/taxbuddy-dashboard/UsabilityA.tsx"),
  "./components/mockups/taxbuddy-dashboard/UsabilityB.tsx": () => import("../components/mockups/taxbuddy-dashboard/UsabilityB.tsx"),
  "./components/mockups/taxbuddy-dashboard/UsabilityC.tsx": () => import("../components/mockups/taxbuddy-dashboard/UsabilityC.tsx"),
  "./components/mockups/taxbuddy-dashboard/VariantA.tsx": () => import("../components/mockups/taxbuddy-dashboard/VariantA.tsx"),
  "./components/mockups/taxbuddy-dashboard/VariantB.tsx": () => import("../components/mockups/taxbuddy-dashboard/VariantB.tsx"),
  "./components/mockups/taxbuddy-dashboard/VariantC.tsx": () => import("../components/mockups/taxbuddy-dashboard/VariantC.tsx"),
  "./components/mockups/taxbuddy-dashboard/VibeDark.tsx": () => import("../components/mockups/taxbuddy-dashboard/VibeDark.tsx"),
  "./components/mockups/taxbuddy-dashboard/VibeQuiet.tsx": () => import("../components/mockups/taxbuddy-dashboard/VibeQuiet.tsx"),
  "./components/mockups/taxbuddy-dashboard/VibeWarm.tsx": () => import("../components/mockups/taxbuddy-dashboard/VibeWarm.tsx"),
  "./components/mockups/onboarding-arc/DataDrama.tsx": () => import("../components/mockups/onboarding-arc/DataDrama.tsx"),
  "./components/mockups/onboarding-arc/GiantType.tsx": () => import("../components/mockups/onboarding-arc/GiantType.tsx"),
  "./components/mockups/onboarding-arc/RaccoonSpeaks.tsx": () => import("../components/mockups/onboarding-arc/RaccoonSpeaks.tsx")
};
